#!/usr/bin/bash

wget https://github.com/git-ecosystem/git-credential-manager/releases/download/v2.6.1/gcm-linux_amd64.2.6.1.deb
sudo dpkg -i gcm-linux_amd64.2.6.1.deb
git-credential-manager configure
rm gcm-linux_amd64.2.6.1.deb
git config --global credential.credentialStore cache
